name: Security Pipeline (Reusable) - STG

on:
  push:
    branches: [ "feature/dependecy-check" ]
  pull_request:
    branches: [ "feature/dependecy-check" ]
  workflow_dispatch:
  workflow_call:
    inputs:
      project-name:
        description: 'Nome do projeto'
        required: false
        type: string
        default: ${{ github.event.repository.name }}
      branch-name:
        description: 'Nome da branch'
        required: false
        type: string
        default: ${{ github.ref_name }}

jobs:
  # Job 1: SCA - Dependency Check
  dependency-check:
    name: üîç SCA - Dependency Check
    runs-on: ubuntu-latest
    environment: STG
    if: ${{ !inputs.skip-dependency-check }}
    steps:
    - name: Checkout c√≥digo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Executar OWASP Dependency-Check
      uses: ./.github/actions/dependency-check
      with:
        nvd-api-key: ${{ secrets.NVD_API_KEY }}
        project-name: ${{ github.event.repository.name }}
        scan-path: '.'
        fail-on-error: ${{ inputs.fail-on-vulnerabilities }}
